<div class="container mt-2">
    <?php 
    if(isset($this->view->erro)){ 
    ?>
    <div class="bg-danger pt-2 text-white row my-2">
        <h5>
        <?php if($this->view->erro == 1){ ?>
        Usuário já existe
        <?php } ?>
        <?php if($this->view->erro == 2){ ?>
        Email já existe
        <?php } ?>
        <?php if($this->view->erro == 3){ ?>
        Senha deve ter no mínimo 6 caracteres
        <?php } ?>
        <?php if($this->view->erro == 4){ ?>
        Os campos senha e confirmar senha devem ser iguais
        <?php } ?>
        </h5>
    </div>
    <?php 
    } 
    ?>
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex justify-content-center my-3">
                        <img src="img/x.jpg" width="15%">
                    </div>
                    <form action="/criar_conta_post" method="post">
                    <div>
                        <h4 class="mb-2">Criar Conta</h4>
                        <div class="mb-3">
                            <span>Já tem uma conta? <a href="/login" class="link-azul">Faça Login</a></span>
                        </div>
                        <div class="mb-3">
                            <label for="username" class="mb-1">Username:</label>
                            <input type="text" id="username" name="username" class="form-control" value="<?= isset($this->view->erro) ? $this->view->username : '' ?>" required>
                        </div>
                        <div class="mb-3">
                            <label for="email" class="mb-1">Email:</label>
                            <input type="email" id="email" name="email" class="form-control" value="<?= isset($this->view->erro) ? $this->view->email : '' ?>" required>
                        </div>
                        <div class="mb-3">
                            <label for="senha" class="mb-1">Senha:</label>
                            <input type="password" id="senha" name="senha" class="form-control" value="<?= isset($this->view->erro) ? $this->view->senha : '' ?>" required>
                        </div>
                        <div class="mb-4">
                            <label for="confirmar_senha" class="mb-1">Confirmar Senha:</label>
                            <input type="password" id="confirmar_senha" name="confirmar_senha" class="form-control" value="<?= isset($this->view->erro) ? $this->view->confirmar_senha : '' ?>" required>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6 offset-3">
                            <input type="submit" value="Criar Conta" class="fw-bold btn btn-primary w-100">
                        </div>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

