<div class="container mt-4">
<?php 
    if(isset($_GET['mensagem_enviada']) && $_GET['mensagem_enviada'] == 1){ 
    ?>
    <div class="bg-success pt-2 text-white row justify-content-center my-4">
        <h5>Email Enviado!</h5>
    </div>
    <?php 
    } 
    ?>
    <?php 
    if(isset($this->view->erro) && $this->view->erro == 1){ 
    ?>
    <div class="bg-danger pt-2 text-white row my-4">
        <h5>Email não cadastrado</h5>
    </div>
    <?php 
    } 
    ?>
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
                    <form action="/enviar_email" method="post">
                    <div>
                        <h4 class="mb-3">Redefinir Senha</h4>
                        <div class="mb-4">
                            <label for="email" class="mb-1">Email:</label>
                            <input type="email" id="email" name="email" class="form-control" value="<?= isset($this->view->erro) ? $this->view->email : '' ?>" required>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6 offset-3">
                            <input type="submit" value="Confirmar" class="fw-bold btn btn-primary w-100 mb-3">
                            <a href="/login" class="fw-bold btn btn-info w-100 mb-1">
                                <i class="fa-solid fa-backward me-2"></i>Voltar
                            </a>
                        </div>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

