<div class="container mt-4">
    <?php 
    if($this->view->erro == 1){ 
    ?>
    <div class="bg-danger pt-2 text-white row my-2">
        <h5>Senha deve ter no mínimo 6 caracteres</h5>
    </div>
    <?php 
    } 
    ?>
    <?php 
    if($this->view->erro == 2){ 
    ?>
    <div class="bg-danger pt-2 text-white row my-2">
        <h5>Os campos senha e confirmar senha devem ser iguais</h5>
    </div>
    <?php 
    } 
    ?>
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
                    <form action="/nova_senha_post" method="post">
                    <div>
                        <div class="mb-4">
                            <label for="senha" class="mb-1">Senha:</label>
                            <input type="password" id="senha" name="senha" class="form-control" value="<?= isset($this->view->erro) ? $this->view->senha : '' ?>" required>
                        </div>
                        <div class="mb-4">
                            <label for="confimar_senha" class="mb-1">Confirmar Senha:</label>
                            <input type="password" id="confimar_senha" name="confirmar_senha" class="form-control" value="<?= isset($this->view->erro) ? $this->view->confirmar_senha : '' ?>" required>
                        </div>
                        <input type="hidden" name="id" value="<?= isset($_GET['id']) ? $_GET['id'] : $this->view->id ?>">
                    </div>
                    <div class="row">
                        <div class="col-6 offset-3">
                            <input type="submit" value="Confirmar" class="fw-bold btn btn-primary w-100 mb-3">
                            <a href="/login" class="fw-bold btn btn-info w-100 mb-1">Login</a>
                        </div>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

