<link rel="stylesheet" href="css/index.css">
<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/">
	  		Home
	  	</a>
	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="img/x.jpg" class="menuIco"/>
	  </div>
	</div>
</nav>
<div class="container mt-5">
	<div class="row pt-2">
		<div class="col-md-3">
			<div class="perfil">
				<div class="perfilTopo"></div>
				<div class="perfilPainel">
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?= $_SESSION['username'] ?></span>
						</div>
					</div>
					<div class="row mb-2">
						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->total_tweets ?></span>
						</div>
						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->total_seguindo ?></span>
						</div>
						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->total_seguidores ?></span>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form method="post" action="/tweet">
						<textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="tweet"></textarea>
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>
					</form>
				</div>
			</div>
            <?php
            foreach($this->view->tweets as $key => $value){
            ?>
			<div class="row tweet">
				<div class="col">
					<p><strong><?= $value['username'] ?></strong><small><span class="text text-muted"> - <?= $value['data'] ?></span></small></p>
					<p><?= $value['tweet'] ?></p>
					<br/>
					<div class="col d-flex justify-content-end">
						<a href="/remover?id=<?= $value['id'] ?>" class="btn btn-danger">Remover</a>
					</div>
				</div>
			</div>
            <?php
            }
            ?>
			<div class="row">
				<nav aria-label="Page navigation example">
					<ul class="pagination">
						<li class="page-item">
							<a class="page-link" href="?pagina=1" aria-label="Previous">
								<span aria-hidden="true">&laquo;</span>
								<span class="sr-only">Previous</span>
							</a>
						</li>
						<?php
						for($i=1;$i<=$this->view->total_paginas;$i++){
						?>
						<li class="page-item">
							<a class="page-link <?= $this->view->pagina_ativa == $i ? 'active' : '' ?>" href="?pagina=<?= $i ?>"><?= $i ?></a>
						</li>
						<?php
						}
						?>
						<li class="page-item">
							<a class="page-link" href="?pagina=<?= $this->view->total_paginas ?>" aria-label="Next">
								<span aria-hidden="true">&raquo;</span>
								<span class="sr-only">Next</span>
							</a>
						</li>
					</ul>
				</nav>
			</div>
		</div>
		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br/>
				<hr/>
				<a href="/quem_seguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>
	</div>
</div>